apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app.kubernetes.io/name: myapp
spec:
  containers:
  - name: nginx-app
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
