apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: voting
spec:
  selector:
    app: result
  ports:
    - port: 5000
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: voting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - name: result
          image: mohamed1780/result:latest
          ports:
            - containerPort: 5000
      resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi