apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: demo-app
  endpoints:
    - port: http        # nom du port DU SERVICE, pas le numéro
      path: /metrics
      interval: 15s