apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-rwo
provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-persistent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-persistent
  template:
    metadata:
      labels:
        app: mysql-persistent
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        - name: MYSQL_DATABASE
          value: "testdb"
        - name: MYSQL_USER
          value: "testuser"
        - name: MYSQL_PASSWORD
          value: "testpass"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc


---

# db-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  username: YWRtaW4=        # admin en base64
  password: cGFzc3dvcmQxMjM= # password123 en base64
  config.properties: |
    ZGJfdXJsPWpkYmM6bXlzcWw6Ly9teXNxbC1zZXJ2aWNlOjMzMDYvdGVzdGRiCmRiX3VzZXI9YWRtaW4KZGJfcGFzc3dvcmQ9cGFzc3dvcmQxMjM=
  # Contenu en base64 : db_url=jdbc:mysql://mysql-service:3306/testdb\ndb_user=admin\ndb_password=password123