apiVersion: v1
kind: Namespace
metadata:
  name: lab

---

apiVersion: v1
kind: Pod
metadata:
  name: ghost-app
  namespace: lab
  labels:
    app.kubernetes.io/name: ghost-app
spec:
  initContainers:
  - name: init-ghost
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'mkdir -p /var/lib/ghost/content/data']

  containers:
  - name: ghost-app
    image: ghost:5-alpine
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 2368
    env:
    - name: database__client
      value: sqlite3
    - name: database__connection__filename
      value: /var/lib/ghost/content/data/ghost.db