apiVersion: v1
kind: Secret
metadata:
  name: voting-secrets
  namespace: voting
type: Opaque
data:
  # echo -n "postgres" | base64   → cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  # echo -n "v0t1ng-p4ss" | base64 → djB0MW5nLXA0c3M=
  POSTGRES_PASSWORD: djB0MW5nLXA0c3M=